Hidden messages
namafutatsu/spotlight pull request #5
Opened 2017-05-13 00:20 UTC by gdrtf

Bon, je sais pas si ça va te plaire, au pire on peut virer. Mais je me suis dit qu'il fallait pouvoir ajouter un message à l'image, un titre ou une connerie. Et puis, ça m'a paru une bonne idée de pouvoir dissimuler ce message DANS l'image. J'ai testé en ajoutant juste du texte simple, mais l'effet est pourri. Je me suis un peu emballé en jouant avec ces histoires de shadowblur, et en fait je trouve le résultat pas trop trop mal. J'ai rien optimisé pour l'instant mais je pense que ça respecte bien l'esprit "projecteur", kestendi ?

2017-05-15 17:48 UTC, vperron requested changes
Des pétits changements (moi je mettrais vraiment que un message et je l'appellerais "titre")

Pour la partie "vérifier que le message est pas trop long pour l'image" il y a surement un truc à faire.

Pour le fichier JSON au lieu d'une BDD, ça va etre long donc je verrais ça plutot dans une autre PR :)

2017-05-15 17:48 UTC, vperron commented on client/spotlight.js
> +    })
marrant, j'aurais plutot vu une fonction `drawMessage(msg)` sur laquelle tu boucles ! CF. plus bas.

2017-05-15 17:48 UTC, vperron commented on client/spotlight.js
> +      ctx.font = message.font
oh je pense que ça sera une feature pour plus tard de changer la font ;)

2017-05-15 17:48 UTC, vperron commented on client/spotlight.js
> +      client.drawMessages()
```javascript
messages.forEach((msg) => drawMessage(msg))
```
ca fait des fonctions plus clean (atomic) . Mais en vrai un seul message suffit pour l'instant IMHO.

2017-05-15 17:48 UTC, vperron commented on server/image.jpg.json
> +]
OK, c'est une forme de base de données ^^

Mais en vrai ça comme l'image "de test" actuelles ne devraient pas etre dans le repository. On va devoir vite s'atteller à la base de données et au stockage des images.

2017-05-15 17:48 UTC, vperron commented on server/ws_server.js
> +  let messages = null
maintenant c'est null et non pas [] ? ;) je dis juste ça pour faire iech' ^^ 

en vrai tu n'as pas besoin de le déclarer ici, je pense, tu peux le faire dans ta fonction qui lit le JSON plus bas.

2017-05-15 17:48 UTC, vperron commented on server/ws_server.js
> +const fs = require('fs')
nit-picking mais j'essaye de garder les imports organisés par ordre alphabétique, et par "paquets":
- import systeme
- imports des libs relatives mais "les notres" (ici on en a pas)
- imports des "fichiers d'a coté"

2017-05-15 17:48 UTC, vperron commented on client/spotlight.js
> +  let messages = []
je mettrais juste un message, genre "le titre", en avoir une collection risque de rendre le tout un peu compliqué (pense plusieurs lignes) sans forcément d'intéret.

Pareillement lors de l'upload il faudra faire attention puisque tu ne peux pas mettre facilement une limite sur le nombre de caractères du titre: en gros tu as droit à une ligne, soit N caractères par pixels de largeur de ton image.

Ou alors on exige une image de au moins 600pixels de large et on propose un "titre" lors de l'upload de 50 caractères max, figé. Pour l'instant.

Si les gens kiffent on rajoutera les multiline, les emojis, etc.

2017-05-15 17:48 UTC, vperron commented on server/ws_server.js
> +    })
pareil, ça marche bien mais je pense que c'est pas une super idée de lire les choses dans un fichier JSON. De plus attention, avec ça tu vas faire un setMessage à un moment un peu random (quand le fichier JSON est lu, ce qui peut arriver un peu n'importe quand) 

Pas gravissime mais juste pour que tu voies la nature "asynchrone" de node.

2017-05-16 06:59 UTC, gdrtf commented on client/spotlight.js
> +  let messages = []
Je pensais justement à ce qui est promotion de spectacle ou jsaispasquoi. Genre tu mets le jour, l'heure, l'adresse, ça tient pas sur une ligne. Au pire on limite au moment de l'upload non ?

2017-05-16 07:02 UTC, gdrtf commented on server/ws_server.js
> +  let messages = null
Non non, t'as raison

2017-05-16 07:02 UTC, gdrtf commented on server/ws_server.js
> +  let messages = null
Hésite pas à faire iech ;)

2017-05-16 07:10 UTC, gdrtf commented on server/ws_server.js
> +    })
J'ai utilisé un JSON en attendant qu'on ait une BDD, je pense pas non plus que ça soit une bonne idée dans le produit final. Mais oui, je suis conscient de l'asynchronicité, c'était voulu :)

2017-05-17 21:09 UTC, vperron commented on client/spotlight.js
> +  let messages = []
bah ok, faudra juste bien le prendre en compte quand on fera la page d'upload !

2022-10-21 03:50 UTC, closed without merging